config/routes.rb
Rails.application.routes.draw do
  root 'session#new'
  # root 'users#index'
  get "/users/edit" => 'users#edit', :as => "edit_user"
  resources :users, :except => [:edit]
  get '/login' => 'session#new', :as => "login"
  post '/login' => 'session#create'
  delete '/logout' => 'session#destroy', :as => "logout"
  get 'recipes/search' => 'recipes#search'
  resources :recipes
end

app/models/categories_recipe.rb
class CategoriesRecipe < ActiveRecord::Base
  has_and_belongs_to_many :recipes
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :users, :through => :recipes
  has_and_belongs_to_many :recipes
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :recipes
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  has_many :users ,:through => :recipes
  has_and_belongs_to_many :recipes
end

app/models/ingredients_recipe.rb
class IngredientsRecipe < ActiveRecord::Base
  has_and_belongs_to_many :recipes
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  belongs_to :user
  has_many :comments
  has_and_belongs_to_many :ingredients
  has_and_belongs_to_many :categories
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :recipes
  has_many :categories, :through => :recipes
  has_many :ingredients, :through => :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :fetch_user

  private
    def fetch_user
      @current_user = User.find_by(:id => session[:user_id]) if session[:user_id]
      session[:user_id] = nil unless @current_user.present?
    end
end

app/controllers/recipes_controller.rb
require 'google/api_client'
class RecipesController < ApplicationController
before_action :set_recipe, only: [:show, :edit, :update, :destroy]
DEVELOPER_KEY =  'AIzaSyDwouYJaSWiuSaJk7u4wjyaBDQGogC_ItU'
YOUTUBE_API_SERVICE_NAME = 'youtube'
YOUTUBE_API_VERSION = 'v3'
  def get_youtube_service
    client = Google::APIClient.new(
      :key => DEVELOPER_KEY,
      :authorization => nil,
      :application_name => $PROGRAM_NAME,
      :application_version => '1.0.0'
    )
    youtube = client.discovered_api(YOUTUBE_API_SERVICE_NAME, YOUTUBE_API_VERSION)
    return client, youtube
  end

  def get_youtube_videos(recipe_name)
  client, youtube = get_youtube_service
  begin

      search_response = client.execute!(
        :api_method => youtube.search.list,
        :parameters => {
          :part => 'snippet',
          :q => recipe_name,
          :maxResults => 3,
          :channelId=>'UCpSgg_ECBj25s9moCDfSTsA'

        }
      )

      all_videos = []
      search_response.data.items.each do |search_result|
        case search_result.id.kind
          when 'youtube#video'
            # videos << "#{search_result.snippet.title} (#{search_result.id.videoId})"
            thumbnail_url= "#{search_result.snippet.thumbnails.high.url} "
            video_id =  "#{search_result.id.videoId}"
            puts video_id
            videoURL ="https://www.youtube.com/watch?v=#{video_id}"
            # puts videoURL
            hrefTagStart="<a href='#{videoURL}'>"
            hrefTagEnd="</a>"
            paraValue= "<img src= '#{thumbnail_url}'style='width:250px;height:250px; margin-right:10px;'>";
              # display output in result area
            youtubeurl=  "#{hrefTagStart}#{paraValue}#{hrefTagEnd}"
            all_videos << youtubeurl.html_safe
        end
      end

    rescue Google::APIClient::TransmissionError => e
      puts e.result.body
    end
    return all_videos
  end


  def index
    @recipes = Recipe.all
  end

  def search
    @recipes = Category.find( params[:category] ).recipes.where(:user_id => @current_user.id)
  end

  def show
    @recipe = Recipe.find( params[:id] )
    @all_video_link = get_youtube_videos("recipe of #{@recipe.name}") if @recipe.name

  end


  def new
    @recipe = Recipe.new
  end


  def edit
  end


  def create
    user = @current_user
    recipe = Recipe.new(recipe_params)
    recipe.user = user

    respond_to do |format|
      if recipe.save
        format.html { redirect_to user_path(User.find_by_id(session[:user_id])), notice: 'recipe was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: recipe.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    # @recipe = Recipe.find(params[:id])
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @recipe.destroy
    respond_to do |format|
      format.html { redirect_to user_path(@current_user), notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end


    def recipe_params
      params.require(:recipe).permit(:name, :image, :instructions, :category_ids, { :ingredient_ids => [] })
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by( :email_id => params[:email_id] )

    if user.present? && user.authenticate( params[:password] )
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "Your password or email is incorrect"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] ="You successfully logged out"
    redirect_to login_path
  end
  end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authorise_user, :except => [:index, :new]
  def index
    @users = User.all

  end

  def show
    @user = User.find( params[:id] )

  end

  def new
     @user = User.new
  end

  def create
    @user = User.new user_params
   if @user.save
     flash[:success] = "User was successfully created"
     redirect_to users_path
   else
     flash[:error] = "The lens cap is on"
     render :new
   end
  end

  def edit
    @user = @current_user
  end

  def update
    user = @current_user
    user.update user_params

    redirect_to user_path(user)
  end

  def destroy
    user = @current_user
    user.destroy

    redirect_to users_path()
  end
  private
   def user_params
     params.require(:user).permit(:email_id, :password, :password_confirmation)
   end

  def authorise_user
     flash[:error] = "You need to be logged in to see that" unless @current_user.present?
     redirect_to login_path unless @current_user.present?
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recipebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%=controller_name%>-<%=action_name%>">

    <nav>
      <% unless @current_user.present? %>
        <%= link_to( "Login", login_path(),:class => "waves-effect waves-light btn" ) %>
        <%= link_to( "Sign up", new_user_path(),:class => "waves-effect waves-light btn" ) %>
      <% else %>
        <%= link_to( "Edit", edit_user_path(@current_user.id) ,:class => "waves-effect waves-light btn") %>
        <%= link_to( "Log out ", logout_path(), :method => :delete,:class => "waves-effect waves-light btn" ) %>
        <%= link_to 'Add Recipe', new_recipe_path,:class => "waves-effect waves-light btn" %>
      <% end %>
    </nav>
    <% if flash[:success] %>
        <h1><%= flash[:success] %></h1>
      <% end %>
      <% if flash[:error] %>
        <h1><%= flash[:error] %></h1>
      <% end %>
<%= yield %>
<script id="dsq-count-scr" src="//recipebook-1.disqus.com/count.js" async></script>
</body>
</html>

app/views/recipes/_form.html.erb
<div class="main_form">
<%= form_for(recipe) do |f| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>
      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :category %>
    <%= f.collection_select(:category_ids, Category.all, :id, :name) %>
</div>

<div class="field">
  <%= f.label :ingredients %>
  <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name %>
</div>

  <div class="field">
    <%= f.label :instructions %>
    <%= f.text_area :instructions, :class=>"materialize-textarea" %>
  </div>

  <div class="actions right-align">
    <%= f.submit :class => "waves-effect waves-light btn" %>
  </div>
<div class="left-align"><%= link_to 'Back',user_path(@current_user),:class => "waves-effect waves-light btn" %></div>

<% end %>
</div>

app/views/recipes/create.html.erb
<h1>Recipe#create</h1>
<p>Find me in app/views/recipe/create.html.erb</p>

app/views/recipes/deastroy.html.erb
<h1>Recipe#deastroy</h1>
<p>Find me in app/views/recipe/deastroy.html.erb</p>

app/views/recipes/edit.html.erb
<!-- <h1>Editing recipe</h1> -->
<%= render 'form', recipe: @recipe %>
<td><%= link_to 'Show', @recipe, :class => "waves-effect waves-light btn" %></td>
<!-- <td><%#= link_to 'Back', user_path(@recipe.user),:class => "waves-effect waves-light btn" %></td> -->

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Instructions</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><img src="<%= recipe.image %>"width="200" height="200" margin-right:"10px"></td>
          <td>
          <% recipe.categories.each do |category| %>
            <%= category.name %>
          <% end %>
          </td>

          <td>
          <% recipe.ingredients.each do |ingredient|  %>
            <%= ingredient.name %>
          <% end %>
          </td>
        <td><%= recipe.instructions %></td>
        <td><%= link_to 'Show', recipe ,:class => "waves-effect waves-light btn"%></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe),:class => "waves-effect waves-light btn" %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' },:class => "waves-effect waves-light btn" %></td>
        <td><%= link_to 'New Recipe', new_recipe_path,:class => "waves-effect waves-light btn" %><td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form', recipe: @recipe %>

app/views/recipes/search.html.erb
<div class="row ">

<% @recipes.each do |recipe| %>
<div class=" col s4 ">
<p><%= recipe.name %></p>
<ul>
    <li>
    <img src="<%= recipe.image %>" style='width:200px;height:200px;margin-left:10px;margin-right:10px;',class="each_image">

</li>
</ul>
        <!-- <ul> -->
          <!-- <%# recipe.comments.each do |m| %> -->
            <!-- <li><%#= m.name %></li> -->
          <%# end %>
        <!-- </ul> -->

        <%= link_to "view recipe", recipe_path( recipe.id ), :method => :get,:class => "waves-effect waves-light btn" %>
        <%= link_to 'Back', user_path(@current_user),:class => "waves-effect waves-light btn" %>
    </div>

<% end %>
</div>

app/views/recipes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @recipe.name %>
</p>

<p>
  <strong>Image:</strong>
  <img src="<%= @recipe.image %>"width="250" height="250" margin-right:"10px">

</p>

<p>
  <strong>Category:</strong>
  <% @recipe.categories.each do |category|  %>
    <%= category.name %>
  <% end %>
</p>


<p>
  <strong>Ingredient:</strong>
  <% @recipe.ingredients.each do |ingredient|  %>
    <%= ingredient.name %>
  <% end %>
</p>
<p>
  <strong>Instructions:</strong>
  <%= @recipe.instructions %>
</p>


<%= link_to 'Edit', edit_recipe_path(@recipe),:class => "waves-effect waves-light btn" %>
<%= link_to 'Back', user_path(@recipe.user),:class => "waves-effect waves-light btn" %>
<%= link_to 'Destroy', @recipe, method: :delete, data: { confirm: 'Are you sure?' } ,:class => "waves-effect waves-light btn"%>


<p>
  <strong>Youtube videos:</strong>
  <% @all_video_link .each do |singleVideoLink|  %>
   <%= singleVideoLink %>
  <% end %>
</p>

<div id="disqus_thread"></div>
<script>

    (function() {
        var d = document, s = d.createElement('script');

        s.src = '//recipebook-1.disqus.com/embed.js';

        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/recipes/update.html.erb
<h1>Recipe#update</h1>
<p>Find me in app/views/recipe/update.html.erb</p>

app/views/session/new.html.erb
<h3>Login </h3>
<div class="initial_page">
<%= form_tag login_path do %>
  <p>
    <div class="colors"> <%= label_tag :email_id %></div>
    <%= email_field_tag :email_id, "", :required => true %>
  </p>
  <p>
    <div class="colors"><%= label_tag :password %></div>
    <%= password_field_tag :password, "", :required => true %>
  </p>

  <%= submit_tag "Login" ,:class => "waves-effect waves-light btn"%>
<% end %>
</div>

app/views/users/_form.html.erb
<% unless @user.errors.full_messages.empty? %>
  <% @user.errors.full_messages.each do |error| %>
    <p><%= error %></p>
  <% end %>
<% end %>
<div class='initial_page'>
<%= form_for @user do |f| %>
  <p>
    <%= f.label :email %>
    <%= f.email_field :email_id, :required => true %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password, :required => true %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, :required => true %>
  </p>

  <%= f.submit "Sign up",:class => "waves-effect waves-light btn"  %>
<% end %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit the user</h1>
<%= render :partial => "form" %>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul>
  <% @users.each do |u| %>
    <li>
      <%= link_to( u.name, user_path( u ) ) %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<!-- <h1>Create a new user</h1> -->
<%= render( :partial => "form" ) %>

app/views/users/show.html.erb
<%= form_tag recipes_search_path, method: :get do |f| %>
<div class="row">
<div class="col s6 right-align "><%= submit_tag 'Search',:class => "search waves-effect waves-light btn" %></div>
<div class="col s6"><%= select_tag 'category',options_for_select(Category.all.map{|el| [el.name, el.id]}), :class => "category"  %></div>

</div>
  <% @user.recipes.each do |recipe| %>
  <% end %>
<% end %>


<div class="search_tag"></div>

<p id="notice"><%= notice %></p>

<div class="row ">

  <% @user.recipes.each do |r| %>
<div class=" col s4 ">
<td><p><%= r.name %></p><td>
<td><img class="z-depth-5" src="<%= r.image %>" style='width:200px;height:200px;margin-left:10px;margin-right:10px;'><br></td>
<td><%= link_to "view recipe", recipe_path( r.id ), :method => :get ,:class => "waves-effect waves-light btn"%></td>
</div>
<% end %>

</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>